### ISSUE TITLE
Dropb Shadow example not working

### ISSUE THREAD

**Issue by SergiySev** [wout/svg.filter.js#8]
[link to example](https://github.com/wout/svg.filter.js#drop-shadow)

Here is working example:
```javascript
var text = view.text('SVG text with drop shadow').fill('#fff');
text.filter(function(add) {
                    add.offset(0, 1).in(add.sourceAlpha);
                    var blur = add.gaussianBlur(1);
                    add.blend(add.source, blur);
})
```

**Comment by james-dowell** [comment]
I'd second this, just had the same issue! Thanks for the working example.

**Comment by steffdev** [comment]
Have the same issue - thanks for the example! Any ideas so far what the issue may be? Drop shadow stopped working after svg.js v2.2.1 potentially caused by svg.js 2.2.3 "added workaround for SvgPathSeg which is removed in Chrome 48 (#409)"? See https://github.com/wout/svg.js/blob/master/CHANGELOG.md

**Comment by benwick** [comment]
Problem only exists in Firefox for me, because of an trailing space in the stdDeviation attribute. Here is my pull request #11

**Comment by Fuzzyma** [comment]
Iam not even sure, what the listString function is doing:

```javascript
  function listString(list) {
    if (!Array.isArray(list))
      return list

    for (var i = 0, l = list.length, s = []; i < l; i++)
      s.push(list[i])

    return s.join(' ')
  }
```

I see no sense in pushing all elements from one array into another array. Cant it be just `return list.join(' ')`?

@rdfriedl can you take a look at this?

@benwick Iam not sure why there is a trailing space. Per definition `join` will only add whitespaces between the array elements and not at the start. So this problem can only happen, when the first elements of the array are empty. Why?

**Comment by rdfriedl** [comment]
i got it working.
i have not idea what the `listString` function what there for.
it was only used on the `gaussianBlur` effect so i removed it an replaced it with this [code](https://github.com/rdfriedl/svg.filter.js/blob/a91fdefed8ded758dfd19e2d0e2ffba3f06d4e5f/src/svg.filter.js#L335) compared to the old [code](https://github.com/rdfriedl/svg.filter.js/blob/23c7c5ec6df47c9a61b1fec20f08828b66fe2c4b/src/svg.filter.js#L335)

also part of the reason your shadow effect dose not work is because your not specifying an input for the blur effect, it should look something like this
```javascript
svg.text('Shadow').fill('red').move(100,100).filter(function(add) {
    //resize the filter so that the shadow dose not get cut off
    add.size(3,3).move(-1,-1)

    var offset = add.offset(3, 5).in(add.sourceAlpha);
    var blur = add.gaussianBlur(1).in(offset);
    add.blend(add.source, blur);
})
```

the reason why the example that is provided in the doc works is because when you chain effects
the input of the effect is set to the effect before it
```javascript
var text = draw.text('SVG text with drop shadow').fill('#fff')

text.filter(function(add) {
  //so in this case the "gaussianBlur" effects input is being set to the offset
  var blur = add.offset(0, 1).in(add.sourceAlpha).gaussianBlur(1)
  
  //but if we call it out here its input defaults to "add.source" or "SourceGraphic"
  var blur2 = add.gaussianBlur(1)

  add.blend(add.source, blur)
})
```

and just because, heres a working [example](http://jsfiddle.net/utvfkucg/6/) *it uses the code i just commited*

**Comment by benwick** [comment]
The trailing space was at the end, like stdDeviation="3 " 

... I really have no idea, what that means. I only know it breaks gaussianBlur in Firefox.

**Comment by Fuzzyma** [comment]
@rdfriedl I like how you "take a look" at things :D
I will merge your PR - i think this issue can be closed then

**Comment by nmg196** [comment]
This example no longer works again.   I get ".filter() is not a function.   Shouldn't it be .filterWith() ?
